# Generated by Django 4.1.2 on 2023-08-01 20:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='users/user.png', null=True, upload_to='users/%Y/%m/%d', verbose_name='Imagen de perfil'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe ingresarse en el formato: '+5399999999'. de hasta 11 dígitos permitidos.", regex='^\\+?1?\\d{8,11}$')], verbose_name='Teléfono'),
        ),
    ]
