# Generated by Django 4.1.2 on 2023-08-27 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_image_alter_userprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='user.jpg', null=True, upload_to='users/%Y/%m/%d', verbose_name='Imagen de perfil'),
        ),
    ]
