# Generated by Django 4.1.2 on 2023-12-28 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockedip',
            name='date_unblocked',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de desbloqueo'),
        ),
    ]
