# Generated by Django 4.0.2 on 2022-07-24 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=50)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'permissions': [('crear_rol', 'Puede crear rol'), ('editar_rol', 'Puede editar rol'), ('listar_rol', 'Puede listar rol'), ('eliminar_rol', 'Puede eliminar rol'), ('asignar_rol', 'Puede asignar rol'), ('crear_rol_sistema', 'Puede crear rol sistema'), ('editar_rol_sistema', 'Puede editar rol sistema'), ('gestion_rol_sistema', 'Puede gestionar rol sistema'), ('listar_rol_sistema', 'Puede listar rol sistema'), ('eliminar_rol_sistema', 'Puede eliminar rol sistema'), ('asignar_rol_sistema', 'Puede asignar rol sistema')],
                'default_permissions': (),
            },
        ),
    ]
