# Generated by Django 4.0.2 on 2022-03-04 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solapin', models.CharField(max_length=7)),
                ('nombre', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=40)),
                ('categoria', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('foto', models.URLField(max_length=110)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('administrador', 'Es Administrador'), ('dependiente', 'Es Dependiente'), ('contador', 'Es Contador')),
            },
        ),
    ]
