# Generated by Django 4.0.2 on 2022-06-22 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominacion', models.CharField(max_length=250)),
                ('url', models.CharField(max_length=250)),
                ('ldap_bind_dn', models.CharField(max_length=250)),
                ('ldap_bind_password', models.CharField(max_length=250)),
                ('ldap_user_search', models.CharField(max_length=250)),
                ('ldap_user_search_scope_tree', models.CharField(max_length=250)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'account_servidor',
                'default_permissions': ('add', 'change', 'delete', 'read'),
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solapin', models.CharField(max_length=7)),
                ('nombre', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=40)),
                ('categoria', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('photo', models.URLField(max_length=110)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cargo', models.CharField(default='Técnico', max_length=255, verbose_name='Cargo')),
                ('ldap', models.BooleanField(default=False, verbose_name='¿Autenticación por LDAP?')),
                ('ip_addres', models.CharField(default='255.255.255.255', max_length=15, verbose_name='Dirección IP permitida')),
                ('default_page_size', models.IntegerField(choices=[('10', '10'), ('20', '20'), ('50', '50'), ('100', '100'), ('200', '200'), ('500', '500')], default=20)),
                ('current_login_status', models.BooleanField(default=False, verbose_name='¿Actualmente logueado?')),
                ('current_ip_address', models.CharField(blank=True, max_length=15, null=True, verbose_name='Dirección IP actual')),
                ('current_failed_login_attemps', models.IntegerField(default=0, verbose_name='Cantidad de intentos de inicio de sesión fallidos')),
                ('be_notified', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'db_table': 'account_user_profile',
                'default_permissions': ('add', 'change', 'delete', 'read'),
            },
        ),
    ]
