# Generated by Django 4.0.2 on 2022-06-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='be_notified',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='current_failed_login_attemps',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='current_ip_address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='current_login_status',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='default_page_size',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='ip_addres',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='ldap',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cargo',
            field=models.CharField(default='Usuario', max_length=255, verbose_name='Cargo'),
        ),
    ]
