# Generated by Django 4.0.2 on 2022-06-23 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_userprofile_be_notified_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'default_permissions': ('add', 'change', 'delete', 'read'), 'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfiles'},
        ),
    ]
