# Generated by Django 4.0.2 on 2022-07-07 15:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='categoria',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message=" El número de teléfono debe ingresarse en el formato: '+999999999'. de hasta 12 dígitos permitidos.", regex='^\\+?1?\\d{9,12}$')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.URLField(default='no_picture.svg', max_length=110, verbose_name='Imagen de perfil'),
        ),
    ]
