# Generated by Django 4.0.2 on 2022-07-07 15:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_userprofile_categoria_userprofile_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='cargo',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message=" El número de teléfono debe ingresarse en el formato: '+999999999'. de hasta 12 dígitos permitidos.", regex='^\\+?1?\\d{9,10}$')]),
        ),
    ]
