# Generated by Django 4.0.2 on 2022-07-07 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='nombre',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='apellidos',
            new_name='last_name',
        ),
    ]
