# Generated by Django 4.0.2 on 2022-08-15 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created'], 'permissions': (('report_product', 'Puede reportar productos'),), 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
    ]
