# Generated by Django 4.0.2 on 2022-07-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, default='no_picture.svg', null=True, upload_to='products'),
        ),
    ]
