# Generated by Django 4.1.2 on 2023-06-03 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_manifestation'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manifestation',
        ),
    ]
