# Generated by Django 4.1.2 on 2023-07-22 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclatures', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoría de producto', 'verbose_name_plural': 'Categorías de los productos'},
        ),
    ]
