# Generated by Django 4.1.2 on 2023-11-25 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='última fecha de modificación')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Categoría del producto')),
            ],
            options={
                'verbose_name': 'Categoría de producto',
                'verbose_name_plural': 'Categorías de los productos',
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atributo', models.CharField(max_length=50, unique=True, verbose_name='Atributo')),
                ('valor', models.CharField(max_length=50, unique=True, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Atributo',
                'verbose_name_plural': 'Atributos',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del producto')),
                ('img', models.ImageField(blank=True, default='no_picture.jpg', help_text='Se recomienda que las imágenes que seleccione tenga el formato PNG o JPG.', null=True, upload_to='products/%Y/%m/%d', verbose_name='Imagen del producto')),
                ('state', models.CharField(choices=[('D', 'Disponible'), ('P', 'Prestado')], default='D', max_length=1, verbose_name='Estado')),
                ('stock', models.PositiveIntegerField(verbose_name='Cantidad de unidades')),
                ('active', models.BooleanField(default=True, help_text='Si no está marcado, le permitirá ocultar el producto sin eliminarlo.', verbose_name='Está activo')),
                ('available', models.BooleanField(default=True, help_text='Marcar si el producto está disponible en el sistema.', verbose_name='Está disponible')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.category', verbose_name='Categoria del producto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-created_at'],
                'permissions': (('report_product', 'Puede reportar productos'),),
            },
        ),
    ]
