# Generated by Django 4.1.2 on 2023-11-08 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True, help_text='Si no está marcado, le permitirá ocultar el producto sin eliminarlo.', verbose_name='Está activo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True, help_text='Marcar si el producto está disponible en el sistema.', verbose_name='Está disponible'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, default='no_picture.jpg', help_text='Se recomienda que las imágenes que seleccione tenga el formato PNG o JPG.', null=True, upload_to='products/%Y/%m/%d', verbose_name='Imagen del producto'),
        ),
    ]
