# Generated by Django 4.1.2 on 2023-06-03 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclatures', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nomenclatures.category', verbose_name='Categoria del producto'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
