# Generated by Django 4.1.2 on 2023-07-22 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_product_category_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, default='no_picture.jpg', null=True, upload_to='products/%Y/%m/%d'),
        ),
    ]
