# Generated by Django 4.0.2 on 2022-07-19 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de devolución')),
                ('description', models.TextField(help_text='Describa para que va a ser utilizado el medio prestado', verbose_name='Descripción')),
                ('state', models.CharField(choices=[('PR', 'Prestado'), ('PE', 'Pendiente'), ('EN', 'Entregado')], default='PR', max_length=2, verbose_name='Estado')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Manifestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'Manifestación',
                'verbose_name_plural': 'Manifestaciones',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant', models.PositiveIntegerField(default=1)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.loan')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Listados_de_productos', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Detalle del préstamo',
                'verbose_name_plural': 'Detalle de los préstamos',
                'ordering': ['id'],
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='loan',
            name='manifestation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.manifestation'),
        ),
        migrations.AddField(
            model_name='loan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
