# Generated by Django 4.0.2 on 2022-06-22 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaini', models.DateField(verbose_name='Fecha de inicio')),
                ('fechafin', models.DateField(verbose_name='Fecha concluida')),
                ('descripcion', models.TextField(help_text='Describa para que va a ser utilizado el medio prestado', verbose_name='Descripción')),
                ('state', models.CharField(choices=[('PR', 'Prestado'), ('PE', 'Pendiente'), ('EN', 'Entregado')], default='PR', max_length=2, verbose_name='Estado')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
                'ordering': ['-fechaini'],
            },
        ),
        migrations.CreateModel(
            name='Manifestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'Manifestación',
                'verbose_name_plural': 'Manifestaciones',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='LoanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='loan.loan')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Listados_de_productos', to='inventory.product')),
            ],
        ),
        migrations.AddField(
            model_name='loan',
            name='manifestation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loan.manifestation'),
        ),
        migrations.AddField(
            model_name='loan',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
    ]
