# Generated by Django 4.0.2 on 2022-08-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_alter_loan_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='state',
            field=models.CharField(choices=[('PE', 'Pendiente a autorización'), ('PR', 'Prestado'), ('EN', 'Entregado')], default='PR', max_length=2, verbose_name='Estado'),
        ),
    ]
