# Generated by Django 4.0.2 on 2022-06-27 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('loan', '0002_alter_loan_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant', models.PositiveIntegerField(default=1)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='loan.loan')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Listados_de_productos', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Detalle del préstamo',
                'verbose_name_plural': 'Detalle de los préstamos',
                'ordering': ['id'],
                'default_permissions': (),
            },
        ),
        migrations.DeleteModel(
            name='LoanItem',
        ),
    ]
