# Generated by Django 4.0.2 on 2022-07-02 14:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_loanproduct_delete_loanitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'ordering': ['-created'], 'verbose_name': 'Préstamo', 'verbose_name_plural': 'Préstamos'},
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='fechaini',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='fechafin',
        ),
        migrations.AddField(
            model_name='loan',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de devolución'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loan',
            name='manifestation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.manifestation'),
        ),
    ]
