# Generated by Django 4.1.2 on 2023-11-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_emailnotification_systemnotification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnotification',
            name='body',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='emailnotification',
            name='email_to',
            field=models.EmailField(max_length=254, verbose_name='Enviar a'),
        ),
        migrations.AlterField(
            model_name='emailnotification',
            name='subject',
            field=models.CharField(max_length=255, verbose_name='Asunto'),
        ),
    ]
