# Generated by Django 4.1.2 on 2023-06-03 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclatures', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='manifestation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomenclatures.manifestation'),
        ),
    ]
