# Generated by Django 4.1.2 on 2023-11-18 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trace',
            name='os',
            field=models.CharField(max_length=100, null=True, verbose_name='sistema operativo'),
        ),
    ]
