# Generated by Django 4.0.2 on 2022-08-15 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_alter_notification_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='level',
            field=models.CharField(choices=[('success', 'success'), ('info', 'info'), ('wrong', 'wrong')], default='info', max_length=20),
        ),
    ]
