# Generated by Django 4.1.2 on 2024-01-10 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_reportdefinition_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportdefinition',
            options={'ordering': ['-last_modified_at'], 'permissions': [('can_duplicate_reportdefinition', 'Can duplicate ReportDefinition')]},
        ),
        migrations.AlterField(
            model_name='reportdefinition',
            name='report_type',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre del reporte'),
        ),
    ]
