# Generated by Django 4.1.2 on 2023-11-25 02:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('P', 'Pendiente a autorización'), ('PR', 'Prestado'), ('A', 'Atrasado'), ('E', 'Entregado')], default='P', max_length=2, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
                'ordering': ['-order__created_at'],
                'permissions': (('report_loan', 'Puede reportar Préstamos'),),
            },
        ),
    ]
