# Generated by Django 4.1.2 on 2023-09-17 01:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('Pendiente', 'Pendiente a autorización'), ('Prestado', 'Prestado'), ('Entregado', 'Entregado'), ('Atrasado', 'Atrasado')], default='Prestado', max_length=9, verbose_name='Estado')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
                'ordering': ['-order__created'],
                'permissions': (('report_loan', 'Puede reportar Préstamos'),),
            },
        ),
    ]
