# Generated by Django 4.0.2 on 2022-09-14 18:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('PE', 'Pendiente a autorización'), ('PR', 'Prestado'), ('EN', 'Entregado')], default='PR', max_length=2, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
                'permissions': (('report_loan', 'Puede reportar Préstamos'),),
            },
        ),
    ]
