# Generated by Django 4.1.2 on 2023-08-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_alter_loan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='state',
            field=models.CharField(choices=[('Pendiente', 'Pendiente a autorización'), ('Prestado', 'Prestado'), ('Entregado', 'Entregado')], default='Prestado', max_length=9, verbose_name='Estado'),
        ),
    ]
