# Generated by Django 4.1.2 on 2023-08-27 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_alter_loan_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='state',
            field=models.CharField(choices=[('Pendiente', 'Pendiente a autorización'), ('Prestado', 'Prestado'), ('Entregado', 'Entregado'), ('Atrasado', 'Atrasado')], default='Prestado', max_length=9, verbose_name='Estado'),
        ),
    ]
